# Generated by Django 4.1.1 on 2022-09-16 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(max_length=20, null=True)),
                ("address", models.CharField(max_length=100, null=True)),
                ("phone", models.CharField(max_length=11, null=True, unique=True)),
                (
                    "nationality",
                    models.CharField(
                        choices=[
                            ("Nigeria", "Nigeria"),
                            ("Ghana", "Ghana"),
                            ("UK", "UK"),
                            ("USA", "USA"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("Abia", "Abia"),
                            ("Oyo", "Oyo"),
                            ("Osun", "Osun"),
                            ("Lagos", "Lagos"),
                            ("Kano", "Kano"),
                            ("Abuja", "Abuja"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "means_of_identity",
                    models.ImageField(null=True, upload_to="identityImage/"),
                ),
                (
                    "particulars",
                    models.FileField(null=True, upload_to="particularsImage/"),
                ),
                (
                    "profile_passport",
                    models.ImageField(null=True, upload_to="staffImage/"),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("CEO", "CEO"),
                            ("GMD", "GMD"),
                            ("CTO", "CTO"),
                            ("Supervisor", "Supervisor"),
                            ("Accountant", "Accountant"),
                            ("Marketer", "Marketer"),
                            ("Staff", "Staff"),
                            ("HR", "HR"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "marital_status",
                    models.CharField(
                        choices=[
                            ("Single", "Single"),
                            ("Married", "Married"),
                            ("Divorce", "Divorce"),
                            ("Complicate", "Complicate"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("staff", models.BooleanField(default=False)),
                (
                    "accont_number",
                    models.CharField(default="22724194556", max_length=11, unique=True),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
