# Generated by Django 4.1.1 on 2022-09-29 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='accont_number',
            field=models.CharField(default='22538555381', max_length=11, unique=True),
        ),
    ]
